county_dict = {'Alachua': 'ALA',
               'Baker': 'BAK',
               'Bay': 'BAY',
               'Bradford': 'BRA',
               'Brevard': 'BRE',
               'Broward': 'BRO',
               'Calhoun': 'CAL',
               'Charlotte': 'CHA',
               'Citrus': 'CIT',
               'Clay': 'CLA',
               'Collier': 'CLL',
               'Columbia': 'CLM',
               'Dade': 'DAD',
               'Desoto': 'DES',
               'Dixie': 'DIX',
               'Duval': 'DUV',
               'Escambia': 'ESC',
               'Flagler': 'FLA',
               'Franklin': 'FRA',
               'Gadsden': 'GAD',
               'Gilchrist': 'GIL',
               'Glades': 'GLA',
               'Gulf': 'GUL',
               'Hamilton': 'HAM',
               'Hardee': 'HAR',
               'Hendry': 'HEN',
               'Hernando': 'HER',
               'Highlands': 'HIG',
               'Hillsborough': 'HIL',
               'Holmes': 'HOL',
               'Indian River': 'IND',
               'Jackson': 'JAC',
               'Jefferson': 'JEF',
               'Lafayette': 'LAF',
               'Lake': 'LAK',
               'Lee': 'LEE',
               'Leon': 'LEO',
               'Levy': 'LEV',
               'Liberty': 'LIB',
               'Madison': 'MAD',
               'Manatee': 'MAN',
               'Marion': 'MRN',
               'Martin': 'MRT',
               'Monroe': 'MON',
               'Nassau': 'NAS',
               'Okaloosa': 'OKA',
               'Okeechobee': 'OKE',
               'Orange': 'ORA',
               'Osceola': 'OSC',
               'Palm Beach': 'PAL',
               'Pasco': 'PAS',
               'Pinellas': 'PIN',
               'Polk': 'POL',
               'Putnam': 'PUT',
               'Santa Rosa': 'SAN',
               'Sarasota': 'SAR',
               'Seminole': 'SEM',
               'St. Johns': 'STJ',
               'St. Lucie': 'STL',
               'Sumter': 'SUM',
               'Suwannee': 'SUW',
               'Taylor': 'TAY',
               'Union': 'UNI',
               'Volusia': 'VOL',
               'Wakulla': 'WAK',
               'Walton': 'WAL',
               'Washington': 'WAS'}